### PR TITLE
[HOTFIX] Updating pytest dependency to fix error

### PR DESCRIPTION
**Pull request by tallamjr**
It was discovered in builds from #79 and #78 a failure has
occurred on Travis

Error:

    TypeError: attrib() got an unexpected keyword argument 'convert'

It appears that `pytest` seems to have the package `attrs` as a dependency.

REF:
    https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert

	modified:   requirements.txt

### CODE REVIEW

**Comment by tallamjr** [comment]
If successful, and then hopefully merged, this should correct build failures found in #78 and #79
